import Header from './components/Header/Header';
import './variables.scss';
import './globals.scss'
import '@/assets/font/font.scss'

export const metadata = {
  title: 'WhoStoleMySleep',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
